# Generated by Django 5.2.6 on 2025-10-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EjercicioTiempoDistancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_id', models.IntegerField(unique=True)),
                ('enunciado_plantilla', models.TextField()),
                ('desarrollo_plantilla', models.TextField(help_text='Para desarrollos simples con .format(). Para los complejos, dejar un placeholder.')),
                ('variables_json', models.TextField(help_text='Un JSON con claves para cada variable y listas de sus posibles valores.')),
                ('unidad_resultado', models.CharField(max_length=20)),
                ('formula_texto', models.CharField(max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
