# Generated by Django 5.2.6 on 2025-10-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicios_vectores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_id', models.IntegerField(unique=True)),
                ('enunciado_plantilla', models.TextField()),
                ('desarrollo_plantilla', models.TextField(help_text='si el desarrollo es simple con .format, si se usa una un funcion simplemente deja un placeholder')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='img/')),
            ],
        ),
        migrations.AlterField(
            model_name='ejerciciotiempodistancia',
            name='desarrollo_plantilla',
            field=models.TextField(help_text='si el desarrollo es simple con .format, si se usa una un funcion simplemente deja un placeholder'),
        ),
    ]
