# Generated by Django 5.2.6 on 2025-10-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0002_ejercicios_vectores_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicios_movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_id', models.IntegerField(unique=True)),
                ('enunciado_plantilla', models.TextField()),
                ('pregunta_plantilla', models.TextField()),
                ('desarrollo_pregunta', models.TextField(help_text='si el desarrollo es simple con .format, si se usa una un funcion simplemente deja un placeholder')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='img/')),
            ],
        ),
    ]
