# Generated by Django 5.2.6 on 2025-10-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0003_ejercicios_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicios_movimiento',
            name='variables_json',
            field=models.TextField(blank=True, help_text='Un JSON con claves para cada variable y listas de sus posibles valores.', null=True),
        ),
        migrations.AddField(
            model_name='ejercicios_vectores',
            name='variables_json',
            field=models.TextField(blank=True, help_text='Un JSON con claves para cada variable y listas de sus posibles valores.', null=True),
        ),
    ]
