# Generated by Django 5.2.6 on 2025-11-02 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0004_ejercicios_movimiento_variables_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjercicioMedicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_id', models.IntegerField(unique=True)),
                ('enunciado_plantilla', models.TextField()),
                ('desarrollo_plantilla', models.TextField(help_text='si el desarrollo es simple con .format, si se usa una un funcion simplemente deja un placeholder')),
                ('variables_json', models.JSONField(blank=True, help_text='Un JSON con claves para cada variable y listas de sus posibles valores.', null=True)),
            ],
        ),
    ]
